/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figurasGeometricas;

/**
 *
 * @author santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Circulo = new javax.swing.JLabel();
        radioCirculo = new javax.swing.JLabel();
        txtCirculoR = new javax.swing.JTextField();
        areaCirculo = new javax.swing.JLabel();
        txtCirculoA = new javax.swing.JTextField();
        perimetroCirculo = new javax.swing.JLabel();
        txtCirculoP = new javax.swing.JTextField();
        btnAreaCirculo = new javax.swing.JButton();
        btnPerimetroCirculo = new javax.swing.JButton();
        btnLimpiarCirculo = new javax.swing.JButton();
        Cuadrado = new javax.swing.JLabel();
        FigurasGeometricas = new javax.swing.JLabel();
        ladoCuadrado = new javax.swing.JLabel();
        txtCuadradoL = new javax.swing.JTextField();
        areaCuadrado = new javax.swing.JLabel();
        txtCuadradoA = new javax.swing.JTextField();
        perimetroCuadrado = new javax.swing.JLabel();
        txtCuadradoP = new javax.swing.JTextField();
        btnAreaCuadrado = new javax.swing.JButton();
        btnPerimetroCuadrado = new javax.swing.JButton();
        btnLimpiarCuadrado = new javax.swing.JButton();
        btnPerimetroRectangulo = new javax.swing.JButton();
        btnLimpiarRectangulo = new javax.swing.JButton();
        Rectangulo = new javax.swing.JLabel();
        baseRectangulo = new javax.swing.JLabel();
        alturaRectangulo = new javax.swing.JLabel();
        areaRectangulo = new javax.swing.JLabel();
        txtRectanguloB = new javax.swing.JTextField();
        txtRectanguloAL = new javax.swing.JTextField();
        txtRectanguloAR = new javax.swing.JTextField();
        btnAreaRectangulo = new javax.swing.JButton();
        btnPerimetroTriangulo = new javax.swing.JButton();
        btnLimpiarTriangulo = new javax.swing.JButton();
        Traingulo = new javax.swing.JLabel();
        baseTriangulo = new javax.swing.JLabel();
        alturaTriangulo = new javax.swing.JLabel();
        areaTriangulo = new javax.swing.JLabel();
        txtTrianguloB = new javax.swing.JTextField();
        txtTrianguloAL = new javax.swing.JTextField();
        txtTrianguloH = new javax.swing.JTextField();
        btnAreaTriangulo = new javax.swing.JButton();
        txtRectanguloP = new javax.swing.JTextField();
        perimetroRectangulo = new javax.swing.JLabel();
        hipotenusaTriangulo = new javax.swing.JLabel();
        txtTrianguloP = new javax.swing.JTextField();
        tipoTriangulo = new javax.swing.JLabel();
        txtTrianguloAR = new javax.swing.JTextField();
        perimetroTriangulo = new javax.swing.JLabel();
        txtTrianguloT = new javax.swing.JTextField();
        btnHipotenusaTriangulo = new javax.swing.JButton();
        btnTipoTriangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Figuras Geométricas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(80, 0));

        Circulo.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        Circulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Circulo.setText("Círculo");

        radioCirculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radioCirculo.setText("Radio");

        txtCirculoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCirculoRActionPerformed(evt);
            }
        });

        areaCirculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaCirculo.setText("Área");

        perimetroCirculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perimetroCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perimetroCirculo.setText("Perímetro");

        btnAreaCirculo.setText("Área");
        btnAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCirculoActionPerformed(evt);
            }
        });

        btnPerimetroCirculo.setText("Perímetro");
        btnPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCirculoActionPerformed(evt);
            }
        });

        btnLimpiarCirculo.setText("Limpiar");
        btnLimpiarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCirculoActionPerformed(evt);
            }
        });

        Cuadrado.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        Cuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cuadrado.setText("Cuadrado");

        FigurasGeometricas.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        FigurasGeometricas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FigurasGeometricas.setText("Figuras Geométricas");

        ladoCuadrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ladoCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ladoCuadrado.setText("Lado");

        txtCuadradoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuadradoLActionPerformed(evt);
            }
        });

        areaCuadrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaCuadrado.setText("Área");

        perimetroCuadrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perimetroCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perimetroCuadrado.setText("Perímetro");

        btnAreaCuadrado.setText("Área");
        btnAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroCuadrado.setText("Perímetro");
        btnPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuadradoActionPerformed(evt);
            }
        });

        btnLimpiarCuadrado.setText("Limpiar");
        btnLimpiarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroRectangulo.setText("Perímetro");
        btnPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRectanguloActionPerformed(evt);
            }
        });

        btnLimpiarRectangulo.setText("Limpiar");
        btnLimpiarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarRectanguloActionPerformed(evt);
            }
        });

        Rectangulo.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        Rectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rectangulo.setText("Rectángulo");

        baseRectangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        baseRectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baseRectangulo.setText("Base");

        alturaRectangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alturaRectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alturaRectangulo.setText("Altura");

        areaRectangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaRectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaRectangulo.setText("Área");

        txtRectanguloB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRectanguloBActionPerformed(evt);
            }
        });

        btnAreaRectangulo.setText("Área");
        btnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroTriangulo.setText("Perímetro");
        btnPerimetroTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTrianguloActionPerformed(evt);
            }
        });

        btnLimpiarTriangulo.setText("Limpiar");
        btnLimpiarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTrianguloActionPerformed(evt);
            }
        });

        Traingulo.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        Traingulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Traingulo.setText("Triángulo Rectángulo");

        baseTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        baseTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baseTriangulo.setText("Base");
        baseTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        baseTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        alturaTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alturaTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alturaTriangulo.setText("Altura");
        alturaTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        alturaTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        areaTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        areaTriangulo.setText("Área");
        areaTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        areaTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        txtTrianguloB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrianguloBActionPerformed(evt);
            }
        });

        txtTrianguloAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrianguloALActionPerformed(evt);
            }
        });

        btnAreaTriangulo.setText("Área");
        btnAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloActionPerformed(evt);
            }
        });

        txtRectanguloP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRectanguloPActionPerformed(evt);
            }
        });

        perimetroRectangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perimetroRectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perimetroRectangulo.setText("Perímetro");

        hipotenusaTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hipotenusaTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hipotenusaTriangulo.setText("Hipotenusa");
        hipotenusaTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        hipotenusaTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        txtTrianguloP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tipoTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoTriangulo.setText("Tipo");
        tipoTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        tipoTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        txtTrianguloAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrianguloARActionPerformed(evt);
            }
        });

        perimetroTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perimetroTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perimetroTriangulo.setText("Perímetro");
        perimetroTriangulo.setMaximumSize(new java.awt.Dimension(80, 0));
        perimetroTriangulo.setMinimumSize(new java.awt.Dimension(80, 0));

        txtTrianguloT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrianguloTActionPerformed(evt);
            }
        });

        btnHipotenusaTriangulo.setText("Hipotenusa");
        btnHipotenusaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotenusaTrianguloActionPerformed(evt);
            }
        });

        btnTipoTriangulo.setText("Tipo");
        btnTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Circulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(areaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCirculoR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCirculoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(perimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCirculoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAreaCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPerimetroCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarCirculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Cuadrado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ladoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(perimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCuadradoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCuadradoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCuadradoL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAreaCuadrado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPerimetroCuadrado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpiarCuadrado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(perimetroTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTrianguloP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(baseTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTrianguloB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(hipotenusaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTrianguloH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alturaTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(areaTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTrianguloT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrianguloAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrianguloAL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnHipotenusaTriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAreaTriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroTriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTipoTriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarTriangulo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Rectangulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(baseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(perimetroRectangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtRectanguloB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(alturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtRectanguloP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(areaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRectanguloAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRectanguloAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Traingulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarRectangulo)))
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FigurasGeometricas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(FigurasGeometricas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Circulo)
                                    .addComponent(Rectangulo))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioCirculo)
                                    .addComponent(txtCirculoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(areaCirculo)
                                    .addComponent(txtCirculoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(perimetroCirculo)
                                    .addComponent(txtCirculoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAreaCirculo)
                                    .addComponent(btnPerimetroCirculo)
                                    .addComponent(btnLimpiarCirculo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(alturaRectangulo)
                                    .addComponent(txtRectanguloAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRectanguloB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baseRectangulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRectanguloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(areaRectangulo)
                                    .addComponent(txtRectanguloAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perimetroRectangulo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPerimetroRectangulo)
                                    .addComponent(btnLimpiarRectangulo)
                                    .addComponent(btnAreaRectangulo))))
                        .addGap(35, 35, 35)
                        .addComponent(Traingulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrianguloAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alturaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrianguloB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baseTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrianguloAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(areaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTrianguloH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hipotenusaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrianguloT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrianguloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perimetroTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHipotenusaTriangulo)
                            .addComponent(btnAreaTriangulo)
                            .addComponent(btnPerimetroTriangulo)
                            .addComponent(btnTipoTriangulo)
                            .addComponent(btnLimpiarTriangulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cuadrado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ladoCuadrado)
                            .addComponent(txtCuadradoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaCuadrado)
                            .addComponent(txtCuadradoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perimetroCuadrado)
                            .addComponent(txtCuadradoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAreaCuadrado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLimpiarCuadrado)
                                .addComponent(btnPerimetroCuadrado)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCirculoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCirculoRActionPerformed
        // TOD add your handling code here:
    }//GEN-LAST:event_txtCirculoRActionPerformed

    private void btnAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCirculoActionPerformed
        double radio = Double.parseDouble(txtCirculoR.getText());
        
        Circulo circulo = new Circulo(radio);
        
        txtCirculoA.setText(String.format( "%.2f", circulo.calcularArea()));
    }//GEN-LAST:event_btnAreaCirculoActionPerformed

    private void btnLimpiarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCirculoActionPerformed
        txtCirculoA.setText("");
        txtCirculoR.setText("");
        txtCirculoP.setText("");
    }//GEN-LAST:event_btnLimpiarCirculoActionPerformed

    private void btnAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuadradoActionPerformed
        double lado = Double.parseDouble(txtCuadradoL.getText());
        
        Cuadrado cuadrado = new Cuadrado(lado);
        
        txtCuadradoA.setText(String.format( "%.2f", cuadrado.calcularArea()));
    }//GEN-LAST:event_btnAreaCuadradoActionPerformed

    private void btnLimpiarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCuadradoActionPerformed
        txtCuadradoA.setText("");
        txtCuadradoL.setText("");
        txtCuadradoP.setText("");
    }//GEN-LAST:event_btnLimpiarCuadradoActionPerformed

    private void btnLimpiarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarRectanguloActionPerformed
        txtRectanguloAR.setText("");
        txtRectanguloAL.setText("");
        txtRectanguloP.setText("");
        txtRectanguloB.setText("");
    }//GEN-LAST:event_btnLimpiarRectanguloActionPerformed

    private void btnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRectanguloActionPerformed
        double base = Double.parseDouble(txtRectanguloB.getText());
        double altura = Double.parseDouble(txtRectanguloAL.getText());
        
        Rectangulo rectangulo = new Rectangulo(base, altura);
        
        txtRectanguloAR.setText(String.format( "%.2f", rectangulo.calcularArea()));
    }//GEN-LAST:event_btnAreaRectanguloActionPerformed

    private void btnAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloActionPerformed
        double base = Double.parseDouble(txtTrianguloB.getText());
        double altura = Double.parseDouble(txtTrianguloAL.getText());
        
        TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
        
        txtTrianguloAR.setText(String.format( "%.2f", triangulo.calcularArea()));
    }//GEN-LAST:event_btnAreaTrianguloActionPerformed

    private void btnLimpiarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTrianguloActionPerformed
        txtTrianguloAR.setText("");
        txtTrianguloAL.setText("");
        txtTrianguloP.setText("");
        txtTrianguloB.setText("");
        txtTrianguloT.setText("");
        txtTrianguloH.setText("");
    }//GEN-LAST:event_btnLimpiarTrianguloActionPerformed

    private void btnHipotenusaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotenusaTrianguloActionPerformed
        double base = Double.parseDouble(txtTrianguloB.getText());
        double altura = Double.parseDouble(txtTrianguloAL.getText());
        
        TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
        
        txtTrianguloH.setText(String.format( "%.2f", triangulo.calcularHipotenusa()));
    }//GEN-LAST:event_btnHipotenusaTrianguloActionPerformed

    private void btnTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoTrianguloActionPerformed
        double base = Double.parseDouble(txtTrianguloB.getText());
        double altura = Double.parseDouble(txtTrianguloAL.getText());
        
        TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
        
        txtTrianguloT.setText(triangulo.determinarTipoTriangulo());
    }//GEN-LAST:event_btnTipoTrianguloActionPerformed

    private void txtTrianguloTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrianguloTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrianguloTActionPerformed

    private void txtTrianguloBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrianguloBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrianguloBActionPerformed

    private void txtTrianguloALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrianguloALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrianguloALActionPerformed

    private void txtTrianguloARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrianguloARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrianguloARActionPerformed

    private void txtCuadradoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuadradoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuadradoLActionPerformed

    private void txtRectanguloBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRectanguloBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRectanguloBActionPerformed

    private void txtRectanguloPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRectanguloPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRectanguloPActionPerformed

    private void btnPerimetroTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTrianguloActionPerformed
        double base = Double.parseDouble(txtTrianguloB.getText());
        double altura = Double.parseDouble(txtTrianguloAL.getText());
        
        TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
        
        txtTrianguloP.setText(String.format( "%.2f", triangulo.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroTrianguloActionPerformed

    private void btnPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCirculoActionPerformed
        double radio = Double.parseDouble(txtCirculoR.getText());
        
        Circulo circulo = new Circulo(radio);
        
        txtCirculoP.setText(String.format( "%.2f", circulo.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroCirculoActionPerformed

    private void btnPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRectanguloActionPerformed
        double base = Double.parseDouble(txtRectanguloB.getText());
        double altura = Double.parseDouble(txtRectanguloAL.getText());
        
        Rectangulo rectangulo = new Rectangulo(base, altura);
        
        txtRectanguloP.setText(String.format( "%.2f", rectangulo.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroRectanguloActionPerformed

    private void btnPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuadradoActionPerformed
        double lado = Double.parseDouble(txtCuadradoL.getText());
        
        Cuadrado cuadrado = new Cuadrado(lado);
        
        txtCuadradoP.setText(String.format( "%.2f", cuadrado.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Circulo;
    private javax.swing.JLabel Cuadrado;
    private javax.swing.JLabel FigurasGeometricas;
    private javax.swing.JLabel Rectangulo;
    private javax.swing.JLabel Traingulo;
    private javax.swing.JLabel alturaRectangulo;
    private javax.swing.JLabel alturaTriangulo;
    private javax.swing.JLabel areaCirculo;
    private javax.swing.JLabel areaCuadrado;
    private javax.swing.JLabel areaRectangulo;
    private javax.swing.JLabel areaTriangulo;
    private javax.swing.JLabel baseRectangulo;
    private javax.swing.JLabel baseTriangulo;
    private javax.swing.JButton btnAreaCirculo;
    private javax.swing.JButton btnAreaCuadrado;
    private javax.swing.JButton btnAreaRectangulo;
    private javax.swing.JButton btnAreaTriangulo;
    private javax.swing.JButton btnHipotenusaTriangulo;
    private javax.swing.JButton btnLimpiarCirculo;
    private javax.swing.JButton btnLimpiarCuadrado;
    private javax.swing.JButton btnLimpiarRectangulo;
    private javax.swing.JButton btnLimpiarTriangulo;
    private javax.swing.JButton btnPerimetroCirculo;
    private javax.swing.JButton btnPerimetroCuadrado;
    private javax.swing.JButton btnPerimetroRectangulo;
    private javax.swing.JButton btnPerimetroTriangulo;
    private javax.swing.JButton btnTipoTriangulo;
    private javax.swing.JLabel hipotenusaTriangulo;
    private javax.swing.JLabel ladoCuadrado;
    private javax.swing.JLabel perimetroCirculo;
    private javax.swing.JLabel perimetroCuadrado;
    private javax.swing.JLabel perimetroRectangulo;
    private javax.swing.JLabel perimetroTriangulo;
    private javax.swing.JLabel radioCirculo;
    private javax.swing.JLabel tipoTriangulo;
    private javax.swing.JTextField txtCirculoA;
    private javax.swing.JTextField txtCirculoP;
    private javax.swing.JTextField txtCirculoR;
    private javax.swing.JTextField txtCuadradoA;
    private javax.swing.JTextField txtCuadradoL;
    private javax.swing.JTextField txtCuadradoP;
    private javax.swing.JTextField txtRectanguloAL;
    private javax.swing.JTextField txtRectanguloAR;
    private javax.swing.JTextField txtRectanguloB;
    private javax.swing.JTextField txtRectanguloP;
    private javax.swing.JTextField txtTrianguloAL;
    private javax.swing.JTextField txtTrianguloAR;
    private javax.swing.JTextField txtTrianguloB;
    private javax.swing.JTextField txtTrianguloH;
    private javax.swing.JTextField txtTrianguloP;
    private javax.swing.JTextField txtTrianguloT;
    // End of variables declaration//GEN-END:variables
}
